	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

	.align 2
Cry_Generic::
	.incbin "sound/direct_sound_samples/cries/cry_rhydon.bin"
	
	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cries/cry_kyogre.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cries/cry_groudon.bin"
	
	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cries/cry_rayquaza.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cries/cry_pikachu.bin"

	.align 2
Cry_Flabebe::
	.incbin "sound/direct_sound_samples/cries/cry_not_flabebe.bin"

	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cries/cry_not_rotom.bin"

	.align 2
Cry_Hoopa::
	.incbin "sound/direct_sound_samples/cries/cry_not_hoopa.bin"

	.align 2
Cry_Manaphy::
	.incbin "sound/direct_sound_samples/cries/cry_not_manaphy.bin"
	
	.align 2
Cry_Egg_Group_Water_1::
	.incbin "sound/direct_sound_samples/cries/cry_seel.bin"
	
	.align 2
Cry_Egg_Group_Water_2::
	.incbin "sound/direct_sound_samples/cries/cry_seel.bin"

	.align 2
Cry_Egg_Group_Water_3::
	.incbin "sound/direct_sound_samples/cries/cry_seel.bin"

	.align 2
Cry_Egg_Group_Dragon::
	.incbin "sound/direct_sound_samples/cries/cry_salamence.bin"

	.align 2
Cry_Egg_Group_Flying:
	.incbin "sound/direct_sound_samples/cries/cry_swablu.bin"

	.align 2
Cry_Egg_Group_Monster:
	.incbin "sound/direct_sound_samples/cries/cry_tropius.bin"

	.align 2
Cry_Egg_Group_Grass:
	.incbin "sound/direct_sound_samples/cries/cry_oddish.bin"

	.align 2
Cry_Egg_Group_Bug:
	.incbin "sound/direct_sound_samples/cries/cry_venomoth.bin"

	.align 2
Cry_Egg_Group_Mineral:
	.incbin "sound/direct_sound_samples/cries/cry_geodude.bin"

	.align 2
Cry_Egg_Group_Field:
	.incbin "sound/direct_sound_samples/cries/cry_aipom.bin"

	.align 2
Cry_Egg_Group_Human_Like:
	.incbin "sound/direct_sound_samples/cries/cry_meditite.bin"

	.align 2
Cry_Egg_Group_Amorphous:
	.incbin "sound/direct_sound_samples/cries/cry_koffing.bin"

	.align 2
Cry_Egg_Group_Fairy:
	.incbin "sound/direct_sound_samples/cries/cry_skitty.bin"

	.align 2
Cry_Egg_Group_Ditto:
	.incbin "sound/direct_sound_samples/cries/cry_ditto.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"

	.align 2
DirectSoundWaveData_puresquare_37::
	.incbin "sound/direct_sound_samples/puresquare_37.bin"

	.align 2
DirectSoundWaveData_puresquare_50::
	.incbin "sound/direct_sound_samples/puresquare_50.bin"

	.align 2
DirectSoundWaveData_dp_808snare_16::
	.incbin "sound/direct_sound_samples/dp_808snare_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c1_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c2_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c3_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_accordion_c4_16::
	.incbin "sound/direct_sound_samples/dp_accordion_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e1_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e2_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e2_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e3_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e3_16.bin"

	.align 2
DirectSoundWaveData_dp_acgt_e4_16::
	.incbin "sound/direct_sound_samples/dp_acgt_e4_16.bin"

	.align 2
DirectSoundWaveData_dp_africa_dr_16::
	.incbin "sound/direct_sound_samples/dp_africa_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_altosax_c3_16::
	.incbin "sound/direct_sound_samples/dp_altosax_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_bass2::
	.incbin "sound/direct_sound_samples/dp_bass2.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1::
	.incbin "sound/direct_sound_samples/dp_bassdr1.bin"

	.align 2
DirectSoundWaveData_dp_bassdr1_16::
	.incbin "sound/direct_sound_samples/dp_bassdr1_16.bin"

	.align 2
DirectSoundWaveData_dp_bassdr2_16::
	.incbin "sound/direct_sound_samples/dp_bassdr2_16.bin"

	.align 2
DirectSoundWaveData_dp_bluesgt_a2_16::
	.incbin "sound/direct_sound_samples/dp_bluesgt_a2_16.bin"

	.align 2
DirectSoundWaveData_dp_cabassa_16::
	.incbin "sound/direct_sound_samples/dp_cabassa_16.bin"

	.align 2
DirectSoundWaveData_dp_castanet_22::
	.incbin "sound/direct_sound_samples/dp_castanet_22.bin"

	.align 2
DirectSoundWaveData_dp_cawbell_16::
	.incbin "sound/direct_sound_samples/dp_cawbell_16.bin"

	.align 2
DirectSoundWaveData_dp_china_cynbal::
	.incbin "sound/direct_sound_samples/dp_china_cynbal.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c1_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c2_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_clavi_c3_16::
	.incbin "sound/direct_sound_samples/dp_clavi_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c1_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c2_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_clean_gt_c3_16::
	.incbin "sound/direct_sound_samples/dp_clean_gt_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_closed_hihat_16::
	.incbin "sound/direct_sound_samples/dp_closed_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_closehight_16::
	.incbin "sound/direct_sound_samples/dp_closehight_16.bin"

	.align 2
DirectSoundWaveData_dp_cymbal1_16::
	.incbin "sound/direct_sound_samples/dp_cymbal1_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c1_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c2_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c3_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_dis_gt_c4_16::
	.incbin "sound/direct_sound_samples/dp_dis_gt_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_b4_16::
	.incbin "sound/direct_sound_samples/dp_disgt_b4_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_c2_16::
	.incbin "sound/direct_sound_samples/dp_disgt_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e1_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e3_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e3_16.bin"

	.align 2
DirectSoundWaveData_dp_disgt_e4_16::
	.incbin "sound/direct_sound_samples/dp_disgt_e4_16.bin"

	.align 2
DirectSoundWaveData_dp_dragon_dr_16::
	.incbin "sound/direct_sound_samples/dp_dragon_dr_16.bin"

	.align 2
DirectSoundWaveData_dp_el_pia2_c3_22::
	.incbin "sound/direct_sound_samples/dp_el_pia2_c3_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia2_c4_22::
	.incbin "sound/direct_sound_samples/dp_el_pia2_c4_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia_c3_22::
	.incbin "sound/direct_sound_samples/dp_el_pia_c3_22.bin"

	.align 2
DirectSoundWaveData_dp_el_pia_c4_22::
	.incbin "sound/direct_sound_samples/dp_el_pia_c4_22.bin"

	.align 2
DirectSoundWaveData_dp_explosion::
	.incbin "sound/direct_sound_samples/dp_explosion.bin"

	.align 2
DirectSoundWaveData_dp_f_horn_c2_16::
	.incbin "sound/direct_sound_samples/dp_f_horn_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_f_horn_c4_16::
	.incbin "sound/direct_sound_samples/dp_f_horn_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c4_16::
	.incbin "sound/direct_sound_samples/dp_flute_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c5_16::
	.incbin "sound/direct_sound_samples/dp_flute_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_flute_c6_16::
	.incbin "sound/direct_sound_samples/dp_flute_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_fretlessbass_d1_16::
	.incbin "sound/direct_sound_samples/dp_fretlessbass_d1_16.bin"

	.align 2
DirectSoundWaveData_dp_glocken_c6_16::
	.incbin "sound/direct_sound_samples/dp_glocken_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_handclup1::
	.incbin "sound/direct_sound_samples/dp_handclup1.bin"

	.align 2
DirectSoundWaveData_dp_harmonica_c3_16::
	.incbin "sound/direct_sound_samples/dp_harmonica_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c3_16::
	.incbin "sound/direct_sound_samples/dp_harp_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c4_16::
	.incbin "sound/direct_sound_samples/dp_harp_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c5_16::
	.incbin "sound/direct_sound_samples/dp_harp_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_harp_c6_16::
	.incbin "sound/direct_sound_samples/dp_harp_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_india_per_16::
	.incbin "sound/direct_sound_samples/dp_india_per_16.bin"

	.align 2
DirectSoundWaveData_dp_kaaroop_16::
	.incbin "sound/direct_sound_samples/dp_kaaroop_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c3_16::
	.incbin "sound/direct_sound_samples/dp_marin_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c4_16::
	.incbin "sound/direct_sound_samples/dp_marin_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_marin_c5_16::
	.incbin "sound/direct_sound_samples/dp_marin_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_merotim_c2_16::
	.incbin "sound/direct_sound_samples/dp_merotim_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_merotim_c3_16::
	.incbin "sound/direct_sound_samples/dp_merotim_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_mute_conga_16::
	.incbin "sound/direct_sound_samples/dp_mute_conga_16.bin" @ used in bw

	.align 2
DirectSoundWaveData_dp_oboe_c3_16::
	.incbin "sound/direct_sound_samples/dp_oboe_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_oct_g3_16::
	.incbin "sound/direct_sound_samples/dp_oct_g3_16.bin"

	.align 2
DirectSoundWaveData_dp_oct_snare_16::
	.incbin "sound/direct_sound_samples/dp_oct_snare_16.bin"

	.align 2
DirectSoundWaveData_dp_octhit_c2_16::
	.incbin "sound/direct_sound_samples/dp_octhit_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_octlow_cs2_16::
	.incbin "sound/direct_sound_samples/dp_octlow_cs2_16.bin"

	.align 2
DirectSoundWaveData_dp_octlowbra_b2_16::
	.incbin "sound/direct_sound_samples/dp_octlowbra_b2_16.bin"

	.align 2
DirectSoundWaveData_dp_open_hihat_16::
	.incbin "sound/direct_sound_samples/dp_open_hihat_16.bin"

	.align 2
DirectSoundWaveData_dp_openhight::
	.incbin "sound/direct_sound_samples/dp_openhight.bin"

	.align 2
DirectSoundWaveData_dp_org1_c2_16::
	.incbin "sound/direct_sound_samples/dp_org1_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c3_16::
	.incbin "sound/direct_sound_samples/dp_org1_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c4_16::
	.incbin "sound/direct_sound_samples/dp_org1_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_org1_c5_16::
	.incbin "sound/direct_sound_samples/dp_org1_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_org4_c3_16::
	.incbin "sound/direct_sound_samples/dp_org4_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_org4_c4_16::
	.incbin "sound/direct_sound_samples/dp_org4_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_org5_c3_16::
	.incbin "sound/direct_sound_samples/dp_org5_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_pedalhight::
	.incbin "sound/direct_sound_samples/dp_pedalhight.bin"

	.align 2
DirectSoundWaveData_dp_pic_g4_16::
	.incbin "sound/direct_sound_samples/dp_pic_g4_16.bin"

	.align 2
DirectSoundWaveData_dp_pic_g5_16::
	.incbin "sound/direct_sound_samples/dp_pic_g5_16.bin"

	.align 2
DirectSoundWaveData_dp_pickbass_e1_16::
	.incbin "sound/direct_sound_samples/dp_pickbass_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_b1_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_b1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_e1_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_power_gt_e2_16::
	.incbin "sound/direct_sound_samples/dp_power_gt_e2_16.bin"

	.align 2
DirectSoundWaveData_dp_reverscyn_16::
	.incbin "sound/direct_sound_samples/dp_reverscyn_16.bin" @ used in bw

	.align 2
DirectSoundWaveData_dp_ridecap::
	.incbin "sound/direct_sound_samples/dp_ridecap.bin"

	.align 2
DirectSoundWaveData_dp_ridecynbal::
	.incbin "sound/direct_sound_samples/dp_ridecynbal.bin"

	.align 2
DirectSoundWaveData_dp_rim1_roop::
	.incbin "sound/direct_sound_samples/dp_rim1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sheiker::
	.incbin "sound/direct_sound_samples/dp_sheiker.bin"

	.align 2
DirectSoundWaveData_dp_slapbass_c1_16::
	.incbin "sound/direct_sound_samples/dp_slapbass_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_slapbass_g1_16::
	.incbin "sound/direct_sound_samples/dp_slapbass_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_sne1_roop::
	.incbin "sound/direct_sound_samples/dp_sne1_roop.bin"

	.align 2
DirectSoundWaveData_dp_sne2_loop::
	.incbin "sound/direct_sound_samples/dp_sne2_loop.bin" @ used in bw

	.align 2
DirectSoundWaveData_dp_sting_bass_e1_16::
	.incbin "sound/direct_sound_samples/dp_sting_bass_e1_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c1_16::
	.incbin "sound/direct_sound_samples/dp_strings_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c2_16::
	.incbin "sound/direct_sound_samples/dp_strings_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c3_16::
	.incbin "sound/direct_sound_samples/dp_strings_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_strings_c4_16::
	.incbin "sound/direct_sound_samples/dp_strings_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c0_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c0_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c1_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c2_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c3_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c4_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c5_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_c6_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_f4_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_f4_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_g1_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_sty_piano_g3_16::
	.incbin "sound/direct_sound_samples/dp_sty_piano_g3_16.bin"

	.align 2
DirectSoundWaveData_dp_sy_clarinet_c3_16::
	.incbin "sound/direct_sound_samples/dp_sy_clarinet_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass1_c2_16::
	.incbin "sound/direct_sound_samples/dp_synbass1_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass2_c1_16::
	.incbin "sound/direct_sound_samples/dp_synbass2_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_synbass_c1_16::
	.incbin "sound/direct_sound_samples/dp_synbass_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_tambourine_16::
	.incbin "sound/direct_sound_samples/dp_tambourine_16.bin"

	.align 2
DirectSoundWaveData_dp_timpany_as_16::
	.incbin "sound/direct_sound_samples/dp_timpany_as_16.bin" @ used in bw

	.align 2
DirectSoundWaveData_dp_timpany_e_16::
	.incbin "sound/direct_sound_samples/dp_timpany_e_16.bin"

	.align 2
DirectSoundWaveData_dp_tom1_16::
	.incbin "sound/direct_sound_samples/dp_tom1_16.bin"

	.align 2
DirectSoundWaveData_dp_tom_16::
	.incbin "sound/direct_sound_samples/dp_tom_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_b4_16::
	.incbin "sound/direct_sound_samples/dp_tp_b4_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_cs3_16::
	.incbin "sound/direct_sound_samples/dp_tp_cs3_16.bin"

	.align 2
DirectSoundWaveData_dp_tp_cs4_16::
	.incbin "sound/direct_sound_samples/dp_tp_cs4_16.bin"

	.align 2
DirectSoundWaveData_dp_triangle_16::
	.incbin "sound/direct_sound_samples/dp_triangle_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c2_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c3_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_trombone_c4_16::
	.incbin "sound/direct_sound_samples/dp_trombone_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c3_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c4_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c5_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_tub_bell_c6_16::
	.incbin "sound/direct_sound_samples/dp_tub_bell_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_tuba_c1_22::
	.incbin "sound/direct_sound_samples/dp_tuba_c1_22.bin"

	.align 2
DirectSoundWaveData_dp_tuba_c2_22::
	.incbin "sound/direct_sound_samples/dp_tuba_c2_22.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c1_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c2_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c3_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c4_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c5_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_vibra_c6_16::
	.incbin "sound/direct_sound_samples/dp_vibra_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c1_16::
	.incbin "sound/direct_sound_samples/dp_violin_c1_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c3_16::
	.incbin "sound/direct_sound_samples/dp_violin_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c4_16::
	.incbin "sound/direct_sound_samples/dp_violin_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_violin_c5_16::
	.incbin "sound/direct_sound_samples/dp_violin_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_whistle_c5_16::
	.incbin "sound/direct_sound_samples/dp_whistle_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_d3_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_d3_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_g1_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_g1_16.bin"

	.align 2
DirectSoundWaveData_dp_woodbass_gs2_16::
	.incbin "sound/direct_sound_samples/dp_woodbass_gs2_16.bin"

	.align 2
DirectSoundWaveData_dp_woodblock_16::
	.incbin "sound/direct_sound_samples/dp_woodblock_16.bin"

	.align 2
DirectSoundWaveData_dp_woodpat_c4_16::
	.incbin "sound/direct_sound_samples/dp_woodpat_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c2_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c2_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c3_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c3_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c4_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c4_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c5_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c5_16.bin"

	.align 2
DirectSoundWaveData_dp_xylphone_c6_16::
	.incbin "sound/direct_sound_samples/dp_xylphone_c6_16.bin"

	.align 2
DirectSoundWaveData_dp_synthkick::
	.incbin "sound/direct_sound_samples/dp_synthkick.bin"

	.align 2
DirectSoundWaveData_dp_synthsnare::
	.incbin "sound/direct_sound_samples/dp_synthsnare.bin"

	.align 2
DirectSoundWaveData_dp_basschoir36::
	.incbin "sound/direct_sound_samples/dp_basschoir36.bin"

	.align 2
DirectSoundWaveData_dp_tenorchoir48::
	.incbin "sound/direct_sound_samples/dp_tenorchoir48.bin"

	.align 2
DirectSoundWaveData_dp_sopranochoir60::
	.incbin "sound/direct_sound_samples/dp_sopranochoir60.bin"

	.align 2
DirectSoundWaveData_dp_orchhitmajor60::
	.incbin "sound/direct_sound_samples/dp_orchhitmajor60.bin"

	.align 2
DirectSoundWaveData_dp_orchhitminor60::
	.incbin "sound/direct_sound_samples/dp_orchhitminor60.bin"

	.align 2
DirectSoundWaveData_dp_sawtoothlead60::
	.incbin "sound/direct_sound_samples/dp_sawtoothlead60.bin"

	.align 2
DirectSoundWaveData_dp_banjo48::
	.incbin "sound/direct_sound_samples/dp_banjo48.bin"

	.align 2
DirectSoundWaveData_dp_banjo60::
	.incbin "sound/direct_sound_samples/dp_banjo60.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano36::
	.incbin "sound/direct_sound_samples/dp_trinitypiano36.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano48::
	.incbin "sound/direct_sound_samples/dp_trinitypiano48.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano60::
	.incbin "sound/direct_sound_samples/dp_trinitypiano60.bin"

	.align 2
DirectSoundWaveData_dp_trinitypiano72::
	.incbin "sound/direct_sound_samples/dp_trinitypiano72.bin"

	.align 2
DirectSoundWaveData_dp_fretnoise60::
	.incbin "sound/direct_sound_samples/dp_fretnoise60.bin"

	.align 2
DirectSoundWaveData_dp_eternaguitar36::
	.incbin "sound/direct_sound_samples/dp_eternaguitar36.bin"

	.align 2
DirectSoundWaveData_dp_spearpillarwind60::
	.incbin "sound/direct_sound_samples/dp_spearpillarwind60.bin"

	.align 2
DirectSoundWaveData_dp_016bongo::
	.incbin "sound/direct_sound_samples/dp_016bongo.bin"

	.align 2
DirectSoundWaveData_dp_053clap::
	.incbin "sound/direct_sound_samples/dp_053clap.bin"

	.align 2
DirectSoundWaveData_dp_060conga::
	.incbin "sound/direct_sound_samples/dp_060conga.bin" @ used in bw

	.align 2
DirectSoundWaveData_dp_062sleigh::
	.incbin "sound/direct_sound_samples/dp_062sleigh.bin"

	.align 2
DirectSoundWaveData_dp_093snare::
	.incbin "sound/direct_sound_samples/dp_093snare.bin" @ used in bw

	.align 2
DirectSoundWaveData_pl_musicbox62::
	.incbin "sound/direct_sound_samples/pl_musicbox62.bin"

	.align 2
DirectSoundWaveData_pl_musicbox79::
	.incbin "sound/direct_sound_samples/pl_musicbox79.bin"

	.align 2
DirectSoundWaveData_hg_000uprigc2::
	.incbin "sound/direct_sound_samples/hg_000uprigc2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_001uprigc3::
	.incbin "sound/direct_sound_samples/hg_001uprigc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_002accorc3::
	.incbin "sound/direct_sound_samples/hg_002accorc3.bin"

	.align 2
DirectSoundWaveData_hg_003accorc4::
	.incbin "sound/direct_sound_samples/hg_003accorc4.bin"

	.align 2
DirectSoundWaveData_hg_004accorc5::
	.incbin "sound/direct_sound_samples/hg_004accorc5.bin"

	.align 2
DirectSoundWaveData_hg_005pnoffc4::
	.incbin "sound/direct_sound_samples/hg_005pnoffc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_006pnoffc5::
	.incbin "sound/direct_sound_samples/hg_006pnoffc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_010bsna3::
	.incbin "sound/direct_sound_samples/hg_010bsna3.bin"

	.align 2
DirectSoundWaveData_hg_011bsnc3::
	.incbin "sound/direct_sound_samples/hg_011bsnc3.bin"

	.align 2
DirectSoundWaveData_hg_012bsne2::
	.incbin "sound/direct_sound_samples/hg_012bsne2.bin"

	.align 2
DirectSoundWaveData_hg_014fhsolob4::
	.incbin "sound/direct_sound_samples/hg_014fhsolob4.bin"

	.align 2
DirectSoundWaveData_hg_015fhsolod4::
	.incbin "sound/direct_sound_samples/hg_015fhsolod4.bin"

	.align 2
DirectSoundWaveData_hg_016fhsolof3::
	.incbin "sound/direct_sound_samples/hg_016fhsolof3.bin"

	.align 2
DirectSoundWaveData_hg_019celloc4::
	.incbin "sound/direct_sound_samples/hg_019celloc4.bin"

	.align 2
DirectSoundWaveData_hg_020celloe3::
	.incbin "sound/direct_sound_samples/hg_020celloe3.bin"

	.align 2
DirectSoundWaveData_hg_021cellog2::
	.incbin "sound/direct_sound_samples/hg_021cellog2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_022china::
	.incbin "sound/direct_sound_samples/hg_022china.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_023claric5::
	.incbin "sound/direct_sound_samples/hg_023claric5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_024clarie4::
	.incbin "sound/direct_sound_samples/hg_024clarie4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_025clarig3::
	.incbin "sound/direct_sound_samples/hg_025clarig3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_027cleanc5::
	.incbin "sound/direct_sound_samples/hg_027cleanc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_028cleane4::
	.incbin "sound/direct_sound_samples/hg_028cleane4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_029cleang2::
	.incbin "sound/direct_sound_samples/hg_029cleang2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_030cleang3::
	.incbin "sound/direct_sound_samples/hg_030cleang3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_031cowbl::
	.incbin "sound/direct_sound_samples/hg_031cowbl.bin"

	.align 2
DirectSoundWaveData_hg_032crash::
	.incbin "sound/direct_sound_samples/hg_032crash.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_033orccym::
	.incbin "sound/direct_sound_samples/hg_033orccym.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_038drawbc3::
	.incbin "sound/direct_sound_samples/hg_038drawbc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_039drawbc4::
	.incbin "sound/direct_sound_samples/hg_039drawbc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_040drawbc5::
	.incbin "sound/direct_sound_samples/hg_040drawbc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_041ampega2::
	.incbin "sound/direct_sound_samples/hg_041ampega2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_042ampega3::
	.incbin "sound/direct_sound_samples/hg_042ampega3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_043rhodc4::
	.incbin "sound/direct_sound_samples/hg_043rhodc4.bin"

	.align 2
DirectSoundWaveData_hg_044rhodc5::
	.incbin "sound/direct_sound_samples/hg_044rhodc5.bin"

	.align 2
DirectSoundWaveData_hg_046fhnsb4::
	.incbin "sound/direct_sound_samples/hg_046fhnsb4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_047fhnsd4::
	.incbin "sound/direct_sound_samples/hg_047fhnsd4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_048fhnsf3::
	.incbin "sound/direct_sound_samples/hg_048fhnsf3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_049glocknc4::
	.incbin "sound/direct_sound_samples/hg_049glocknc4.bin"

	.align 2
DirectSoundWaveData_hg_050glocknc5::
	.incbin "sound/direct_sound_samples/hg_050glocknc5.bin"

	.align 2
DirectSoundWaveData_hg_051pnoc2::
	.incbin "sound/direct_sound_samples/hg_051pnoc2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_052pnoc3::
	.incbin "sound/direct_sound_samples/hg_052pnoc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_053pnoc4::
	.incbin "sound/direct_sound_samples/hg_053pnoc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_054pnoc5::
	.incbin "sound/direct_sound_samples/hg_054pnoc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_055pnoc6::
	.incbin "sound/direct_sound_samples/hg_055pnoc6.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_058harpc3::
	.incbin "sound/direct_sound_samples/hg_058harpc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_059harpc4::
	.incbin "sound/direct_sound_samples/hg_059harpc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_060harpc5::
	.incbin "sound/direct_sound_samples/hg_060harpc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_062chh::
	.incbin "sound/direct_sound_samples/hg_062chh.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_063ohh::
	.incbin "sound/direct_sound_samples/hg_063ohh.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_065kotoa4::
	.incbin "sound/direct_sound_samples/hg_065kotoa4.bin"

	.align 2
DirectSoundWaveData_hg_066kotoc4::
	.incbin "sound/direct_sound_samples/hg_066kotoc4.bin"

	.align 2
DirectSoundWaveData_hg_067kotoe3::
	.incbin "sound/direct_sound_samples/hg_067kotoe3.bin"

	.align 2
DirectSoundWaveData_hg_068marimc4::
	.incbin "sound/direct_sound_samples/hg_068marimc4.bin"

	.align 2
DirectSoundWaveData_hg_069marimc5::
	.incbin "sound/direct_sound_samples/hg_069marimc5.bin"

	.align 2
DirectSoundWaveData_hg_070marimc6::
	.incbin "sound/direct_sound_samples/hg_070marimc6.bin"

	.align 2
DirectSoundWaveData_hg_071musboxc4::
	.incbin "sound/direct_sound_samples/hg_071musboxc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_072musboxc5::
	.incbin "sound/direct_sound_samples/hg_072musboxc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_073musboxc6::
	.incbin "sound/direct_sound_samples/hg_073musboxc6.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_075nylonc5::
	.incbin "sound/direct_sound_samples/hg_075nylonc5.bin"

	.align 2
DirectSoundWaveData_hg_076nylone4::
	.incbin "sound/direct_sound_samples/hg_076nylone4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_077nylong2::
	.incbin "sound/direct_sound_samples/hg_077nylong2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_078nylong3::
	.incbin "sound/direct_sound_samples/hg_078nylong3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_079oboea5::
	.incbin "sound/direct_sound_samples/hg_079oboea5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_080oboec5::
	.incbin "sound/direct_sound_samples/hg_080oboec5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_081oboee4::
	.incbin "sound/direct_sound_samples/hg_081oboee4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_082octpnoc2::
	.incbin "sound/direct_sound_samples/hg_082octpnoc2.bin"

	.align 2
DirectSoundWaveData_hg_083octpnoc3::
	.incbin "sound/direct_sound_samples/hg_083octpnoc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_084octpnoc4::
	.incbin "sound/direct_sound_samples/hg_084octpnoc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_085octpnoc5::
	.incbin "sound/direct_sound_samples/hg_085octpnoc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_086orchitc4::
	.incbin "sound/direct_sound_samples/hg_086orchitc4.bin"

	.align 2
DirectSoundWaveData_hg_087orchitc5::
	.incbin "sound/direct_sound_samples/hg_087orchitc5.bin"

	.align 2
DirectSoundWaveData_hg_088orchitc6::
	.incbin "sound/direct_sound_samples/hg_088orchitc6.bin"

	.align 2
DirectSoundWaveData_hg_089orchitg5::
	.incbin "sound/direct_sound_samples/hg_089orchitg5.bin"

	.align 2
DirectSoundWaveData_hg_091jazorgc3::
	.incbin "sound/direct_sound_samples/hg_091jazorgc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_092jazorgc4::
	.incbin "sound/direct_sound_samples/hg_092jazorgc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_093jazorgc5::
	.incbin "sound/direct_sound_samples/hg_093jazorgc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_094flt1a4::
	.incbin "sound/direct_sound_samples/hg_094flt1a4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_095flt1c4::
	.incbin "sound/direct_sound_samples/hg_095flt1c4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_096flt1c6::
	.incbin "sound/direct_sound_samples/hg_096flt1c6.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_097flt1f5::
	.incbin "sound/direct_sound_samples/hg_097flt1f5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_098pizza4::
	.incbin "sound/direct_sound_samples/hg_098pizza4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_099pizzc4::
	.incbin "sound/direct_sound_samples/hg_099pizzc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_100pizze3::
	.incbin "sound/direct_sound_samples/hg_100pizze3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_101pizzf5::
	.incbin "sound/direct_sound_samples/hg_101pizzf5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_102pizzg2::
	.incbin "sound/direct_sound_samples/hg_102pizzg2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_114splash::
	.incbin "sound/direct_sound_samples/hg_114splash.bin"

	.align 2
DirectSoundWaveData_hg_115martinc5::
	.incbin "sound/direct_sound_samples/hg_115martinc5.bin"

	.align 2
DirectSoundWaveData_hg_116martine4::
	.incbin "sound/direct_sound_samples/hg_116martine4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_117marting2::
	.incbin "sound/direct_sound_samples/hg_117marting2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_118marting3::
	.incbin "sound/direct_sound_samples/hg_118marting3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_119str1a4::
	.incbin "sound/direct_sound_samples/hg_119str1a4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_120str1c4::
	.incbin "sound/direct_sound_samples/hg_120str1c4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_121str1c6::
	.incbin "sound/direct_sound_samples/hg_121str1c6.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_122str1f5::
	.incbin "sound/direct_sound_samples/hg_122str1f5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_123elastkc2::
	.incbin "sound/direct_sound_samples/hg_123elastkc2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_124elastkc3::
	.incbin "sound/direct_sound_samples/hg_124elastkc3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_125squarc4::
	.incbin "sound/direct_sound_samples/hg_125squarc4.bin"

	.align 2
DirectSoundWaveData_hg_126squarc5::
	.incbin "sound/direct_sound_samples/hg_126squarc5.bin"

	.align 2
DirectSoundWaveData_hg_127squarc6::
	.incbin "sound/direct_sound_samples/hg_127squarc6.bin"

	.align 2
DirectSoundWaveData_hg_128jdruml::
	.incbin "sound/direct_sound_samples/hg_128jdruml.bin"

	.align 2
DirectSoundWaveData_hg_129jdrumm::
	.incbin "sound/direct_sound_samples/hg_129jdrumm.bin"

	.align 2
DirectSoundWaveData_hg_130jdrumh::
	.incbin "sound/direct_sound_samples/hg_130jdrumh.bin"

	.align 2
DirectSoundWaveData_hg_132timpc4::
	.incbin "sound/direct_sound_samples/hg_132timpc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_133timpg3::
	.incbin "sound/direct_sound_samples/hg_133timpg3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_134timpg4::
	.incbin "sound/direct_sound_samples/hg_134timpg4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_135tom::
	.incbin "sound/direct_sound_samples/hg_135tom.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_136tom::
	.incbin "sound/direct_sound_samples/hg_136tom.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_137tom::
	.incbin "sound/direct_sound_samples/hg_137tom.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_138tom::
	.incbin "sound/direct_sound_samples/hg_138tom.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_140tbnc4::
	.incbin "sound/direct_sound_samples/hg_140tbnc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_141tbne3::
	.incbin "sound/direct_sound_samples/hg_141tbne3.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_142tbng2::
	.incbin "sound/direct_sound_samples/hg_142tbng2.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_143tpta4::
	.incbin "sound/direct_sound_samples/hg_143tpta4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_144tptc4::
	.incbin "sound/direct_sound_samples/hg_144tptc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_145tptg5::
	.incbin "sound/direct_sound_samples/hg_145tptg5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_146tbellc5::
	.incbin "sound/direct_sound_samples/hg_146tbellc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_147tbellg4::
	.incbin "sound/direct_sound_samples/hg_147tbellg4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_148vibrc4::
	.incbin "sound/direct_sound_samples/hg_148vibrc4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_149vibrc5::
	.incbin "sound/direct_sound_samples/hg_149vibrc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_150violna5::
	.incbin "sound/direct_sound_samples/hg_150violna5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_151violnc5::
	.incbin "sound/direct_sound_samples/hg_151violnc5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_152violne4::
	.incbin "sound/direct_sound_samples/hg_152violne4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_155xylo1a4::
	.incbin "sound/direct_sound_samples/hg_155xylo1a4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_156xylo1c4::
	.incbin "sound/direct_sound_samples/hg_156xylo1c4.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_157xylo1f5::
	.incbin "sound/direct_sound_samples/hg_157xylo1f5.bin" @ used in bw

	.align 2
DirectSoundWaveData_hg_shamisend3::
	.incbin "sound/direct_sound_samples/hg_shamisend3.bin"

	.align 2
DirectSoundWaveData_hg_shamisenas3::
	.incbin "sound/direct_sound_samples/hg_shamisenas3.bin"

	.align 2
DirectSoundWaveData_hg_shamiseng4::
	.incbin "sound/direct_sound_samples/hg_shamiseng4.bin"

	.align 2
DirectSoundWaveData_hg_pno4c2::
	.incbin "sound/direct_sound_samples/hg_pno4c2.bin"

	.align 2
DirectSoundWaveData_hg_pno4a2::
	.incbin "sound/direct_sound_samples/hg_pno4a2.bin"

	.align 2
DirectSoundWaveData_hg_pno4f3::
	.incbin "sound/direct_sound_samples/hg_pno4f3.bin"

	.align 2
DirectSoundWaveData_hg_pno4d4::
	.incbin "sound/direct_sound_samples/hg_pno4d4.bin"

	.align 2
DirectSoundWaveData_hg_pno4b4::
	.incbin "sound/direct_sound_samples/hg_pno4b4.bin"

	.align 2
DirectSoundWaveData_hg_pno4g5::
	.incbin "sound/direct_sound_samples/hg_pno4g5.bin"

	.align 2
DirectSoundWaveData_hg_pno4e6::
	.incbin "sound/direct_sound_samples/hg_pno4e6.bin"

	.align 2
DirectSoundWaveData_hg_hyoshigi::
	.incbin "sound/direct_sound_samples/hg_hyoshigi.bin"

	.align 2
DirectSoundWaveData_hg_ecruteaklow::
	.incbin "sound/direct_sound_samples/hg_ecruteaklow.bin"

	.align 2
DirectSoundWaveData_hg_tsuzumi::
	.incbin "sound/direct_sound_samples/hg_tsuzumi.bin"

	.align 2
DirectSoundWaveData_hg_jinglebell::
	.incbin "sound/direct_sound_samples/hg_jinglebell.bin"

	.align 2
DirectSoundWaveData_hg_hoohclap::
	.incbin "sound/direct_sound_samples/hg_hoohclap.bin"

	.align 2
DirectSoundWaveData_hg_choirc5::
	.incbin "sound/direct_sound_samples/hg_choirc5.bin" @ used in bw
