#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_AbnormalWeatherEnded_Rain:: @ 8273656
	.string "Parece que el gran aguacero\n"
	.string "ha parado…$"

gText_AbnormalWeatherEnded_Sun:: @ 8273684
	.string "Parece que el intenso brillo del\n"
	.string "sol ha remitido…$"
#else
gText_AbnormalWeatherEnded_Rain:: @ 8273656
	.string "The massive downpour appears to\n"
	.string "have stopped…$"

gText_AbnormalWeatherEnded_Sun:: @ 8273684
	.string "The intense sunshine appears to\n"
	.string "have subsided…$"
#endif
