#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Hola. Éste es el Centro Pokémon.\p"
    .string "Nosotros curamos a los Pokémon\n"
    .string "debilitados.\p"
    .string "¿Quieres que nos ocupemos\n"
    .string "de los Pokémon de tu equipo?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Muy bien. Ten un poco de paciencia.\n"
    .string "Será sólo un momento.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Gracias por esperar.\p"
    .string "Misión cumplida. Somos especialistas\n"
    .string "en devolver la forma a los Pokémon.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "¡Vuelve cuando quieras!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "Hola. Éste es el Centro Pokémon.\p"
    .string "Nosotros curamos a los Pokémon\n"
    .string "debilitados.\p"
    .string "¿Quieres que…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Esa Ficha…\n"
    .string "¿Es…? ¡¿Es de color Oro?!\p"
    .string "¡Oh, ese color es resplandenciente!\n"
    .string "¡Las cuatro estrellas brillan tanto!\p"
    .string "Ya he visto a varios Entrenadores\n"
    .string "con una Ficha de color Plata, pero,\l"
    .string "{PLAYER}, ¡nunca antes había visto\l"
    .string "a nadie con una Ficha de color Oro!\p"
    .string "Muy bien, {PLAYER}, concédeme\n"
    .string "el honor de curar a tus Pokémon.$"

gText_YouWantTheUsual:: @ 8272982
    .string "¡Qué alegría verte, {PLAYER}!\n"
    .string "Lo de siempre, ¿no?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Muy bien. Ten un poco de paciencia.\n"
    .string "Será sólo un momento.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "¡Vuelve cuando quieras!$"
#else
gText_WouldYouLikeToRestYourPkmn:: @ 82726EB
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn:: @ 8272768
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_RestoredPkmnToFullHealth:: @ 8272798
    .string "Thank you for waiting.\p"
    .string "We've restored your Pokémon\n"
    .string "to full health.$"

gText_WeHopeToSeeYouAgain:: @ 82727DB
    .string "We hope to see you again!$"

gText_WelcomeCutShort:: @ 82727F5
    .string "Hello, and welcome to\n"
    .string "the Pokémon Center.\p"
    .string "We restore your tired Pokémon\n"
    .string "to full health.\p"
    .string "Would you like to…$"

gText_NoticesGoldCard:: @ 8272860
    .string "Th-that card…\n"
    .string "Could it be… The Gold Card?!\p"
    .string "Oh, the gold color is brilliant!\n"
    .string "The four stars seem to sparkle!\p"
    .string "I've seen several Trainers with\n"
    .string "a Silver Card before, but, {PLAYER},\l"
    .string "you're the first Trainer I've ever\l"
    .string "seen with a Gold Card!\p"
    .string "Okay, {PLAYER}, please allow me\n"
    .string "the honor of resting your Pokémon!$"

gText_YouWantTheUsual:: @ 8272982
    .string "I'm delighted to see you, {PLAYER}!\n"
    .string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2:: @ 82729C0
    .string "Okay, I'll take your Pokémon\n"
    .string "for a few seconds.$"

gText_ThankYouForWaiting:: @ 82729F0
    .string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2:: @ 8272A07
    .string "We hope to see you again!$"

#endif
