Route102_EventScript_ItemPotion:: @ 8290CD8
	addscaleditem ITEM_POTION
	end

Route103_EventScript_ItemGuardSpec:: @ 8290CE5
	addscaleditem ITEM_GUARD_SPEC
	end

Route103_EventScript_ItemPPUp:: @ 8290CF2
	addscaleditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp:: @ 8290CFF
	addscaleditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall:: @ 8290D0C
	addscaleditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy:: @ 8290D19
	addscaleditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion:: @ 8290D26
	addscaleditem ITEM_POTION
	end

Route105_EventScript_ItemIron:: @ 8290D33
	addscaleditem ITEM_IRON
	end

Route106_EventScript_ItemProtein:: @ 8290D40
	addscaleditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece:: @ 8290D4D
	addscaleditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp:: @ 8290D5A
	addscaleditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion:: @ 8290D67
	addscaleditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy:: @ 8290D74
	addscaleditem ITEM_UP_GRADE
	end

Route110_EventScript_ItemDireHit:: @ 8290D81
	addscaleditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir:: @ 8290D8E
	addscaleditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37:: @ 8290D9B
	addscaleditem ITEM_TM37
	end

Route111_EventScript_ItemStardust:: @ 8290DA8
	addscaleditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp:: @ 8290DB5
	addscaleditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir:: @ 8290DC2
	addscaleditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget:: @ 8290DCF
	addscaleditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther:: @ 8290DDC
	addscaleditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel:: @ 8290DE9
	addscaleditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion:: @ 8290DF6
	addscaleditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy:: @ 8290E03
	addscaleditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein:: @ 8290E10
	addscaleditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder:: @ 8290E1D
	addscaleditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion:: @ 8290E2A
	addscaleditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTM01:: @ 8290E37
	addscaleditem ITEM_TM01
	end

Route115_EventScript_ItemIron:: @ 8290E44
	addscaleditem ITEM_FOCUS_SASH
	end

Route115_EventScript_ItemGreatBall:: @ 8290E51
	addscaleditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder:: @ 8290E5E
	addscaleditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp:: @ 8290E6B
	addscaleditem ITEM_PP_UP
	end

Route116_EventScript_ItemXSpecial:: @ 8290E78
	addscaleditem ITEM_X_SP_ATK
	end

Route116_EventScript_ItemEther:: @ 8290E85
	addscaleditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel:: @ 8290E92
	addscaleditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp:: @ 8290E9F
	addscaleditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion:: @ 8290EAC
	addscaleditem ITEM_POTION
	end

Route117_EventScript_ItemGreatBall:: @ 8290EB9
	addscaleditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive:: @ 8290EC6
	addscaleditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion:: @ 8290ED3
	addscaleditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel:: @ 8290EE0
	addscaleditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc:: @ 8290EED
	addscaleditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir:: @ 8290EFA
	addscaleditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone:: @ 8290F07
	addscaleditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy:: @ 8290F14
	addscaleditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion:: @ 8290F21
	addscaleditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2:: @ 8290F2E
	addscaleditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2:: @ 8290F3B
	addscaleditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget:: @ 8290F48
	addscaleditem ITEM_BLACK_SLUDGE
	end

Route120_EventScript_ItemFullHeal:: @ 8290F55
	addscaleditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion:: @ 8290F62
	addscaleditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall:: @ 8290F6F
	addscaleditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive:: @ 8290F7C
	addscaleditem ITEM_REVIVE
	end

Route121_EventScript_ItemCarbos:: @ 8290F89
	addscaleditem ITEM_CARBOS
	end

Route121_EventScript_ItemRevive:: @ 8290F96
	addscaleditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc:: @ 8290FA3
	addscaleditem ITEM_ZINC
	end

Route123_EventScript_ItemCalcium:: @ 8290FB0
	addscaleditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall:: @ 8290FBD
	addscaleditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir:: @ 8290FCA
	addscaleditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp:: @ 8290FD7
	addscaleditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb:: @ 8290FE4
	addscaleditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard:: @ 8290FF1
	addscaleditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard:: @ 8290FFE
	addscaleditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard:: @ 829100B
	addscaleditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl:: @ 8291018
	addscaleditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard:: @ 8291025
	addscaleditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc:: @ 8291032
	addscaleditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos:: @ 829103F
	addscaleditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy:: @ 829104C
	addscaleditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy:: @ 8291059
	addscaleditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein:: @ 8291066
	addscaleditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl:: @ 8291073
	addscaleditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece:: @ 8291080
	addscaleditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive:: @ 829108D
	addscaleditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos:: @ 829109A
	addscaleditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece:: @ 82910A7
	addscaleditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive:: @ 82910B4
	addscaleditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemEther:: @ 82910C1
	addscaleditem ITEM_ETHER
	end

MauvilleCity_EventScript_ItemXSpeed:: @ 82910CE
	addscaleditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend:: @ 82910DB
	addscaleditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel:: @ 82910E8
	addscaleditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall:: @ 82910F5
	addscaleditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack:: @ 8291102
	addscaleditem ITEM_X_ATTACK
	end

PetalburgWoods_EventScript_ItemGreatBall:: @ 829110F
	addscaleditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther:: @ 829111C
	addscaleditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal:: @ 8291129
	addscaleditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemPokeBall:: @ 8291136
	addscaleditem ITEM_POKE_BALL
	end

RusturfTunnel_EventScript_ItemMaxEther:: @ 8291143
	addscaleditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemEscapeRope:: @ 8291150
	addscaleditem ITEM_ESCAPE_ROPE
	end

GraniteCave_B1F_EventScript_ItemPokeBall:: @ 829115D
	addscaleditem ITEM_POKE_BALL
	end

GraniteCave_B2F_EventScript_ItemRepel:: @ 829116A
	addscaleditem ITEM_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy:: @ 8291177
	addscaleditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal:: @ 8291184
	addscaleditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemFireStone:: @ 8291191
	addscaleditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06:: @ 829119E
	addscaleditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23:: @ 82911AB
	addscaleditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal:: @ 82911B8
	addscaleditem ITEM_FULL_HEAL
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone:: @ 82911C5
	addscaleditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP:: @ 82911D2
	addscaleditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02:: @ 82911DF
	addscaleditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraBall:: @ 82911EC
	addscaleditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope:: @ 82911F9
	addscaleditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone:: @ 8291206
	addscaleditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal:: @ 8291213
	addscaleditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal:: @ 8291220
	addscaleditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail:: @ 829122D
	addscaleditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope:: @ 829123A
	addscaleditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall:: @ 8291247
	addscaleditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13:: @ 8291254
	addscaleditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive:: @ 8291261
	addscaleditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey:: @ 829126E
	addscaleditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall:: @ 829127B
	addscaleditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner:: @ 8291288
	addscaleditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone:: @ 8291295
	addscaleditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18:: @ 82912A2
	addscaleditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11:: @ 82912AF
	addscaleditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22:: @ 82912BC
	addscaleditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium:: @ 82912C9
	addscaleditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive:: @ 82912D6
	addscaleditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget:: @ 82912E3
	addscaleditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl:: @ 82912F0
	addscaleditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemUltraBall:: @ 82912FD
	addscaleditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel:: @ 829130A
	addscaleditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense:: @ 8291317
	addscaleditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense:: @ 8291324
	addscaleditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30:: @ 8291331
	addscaleditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion:: @ 829133E
	addscaleditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM48:: @ 829134B
	addscaleditem ITEM_TM48
	end

AquaHideout_B1F_EventScript_ItemMasterBall:: @ 8291358
	addscaleditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget:: @ 8291365
	addscaleditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir:: @ 8291372
	addscaleditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall:: @ 829137F
	addscaleditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall:: @ 829138C
	addscaleditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget:: @ 8291399
	addscaleditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir:: @ 82913A6
	addscaleditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall:: @ 82913B3
	addscaleditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl:: @ 82913C0
	addscaleditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy:: @ 82913CD
	addscaleditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal:: @ 82913DA
	addscaleditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07:: @ 82913E7
	addscaleditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce:: @ 82913F4
	addscaleditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26:: @ 8291401
	addscaleditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail:: @ 829140E
	addscaleditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail:: @ 829141B
	addscaleditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail:: @ 8291428
	addscaleditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail:: @ 8291435
	addscaleditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail:: @ 8291442
	addscaleditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail:: @ 829144F
	addscaleditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail:: @ 829145C
	addscaleditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail:: @ 8291469
	addscaleditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail:: @ 8291476
	addscaleditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir:: @ 8291483
	addscaleditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp:: @ 8291490
	addscaleditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29:: @ 829149D
	addscaleditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore:: @ 82914AA
	addscaleditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal:: @ 82914B7
	addscaleditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp:: @ 82914C4
	addscaleditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos:: @ 82914D1
	addscaleditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy:: @ 82914DE
	addscaleditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_MaxElixir:: @ 82914EB
	addscaleditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore:: @ 82914F8
	addscaleditem ITEM_FULL_RESTORE
	end

MagmaHideout_3F_1R_EventScript_ItemNugget:: @ 8291505
	addscaleditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax:: @ 8291512
	addscaleditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_MaxRevive:: @ 829151F
	addscaleditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope:: @ 829152C
	addscaleditem ITEM_ESCAPE_ROPE
	end

ScorchedSlab_EventScript_ItemTyranitarite::
	addscaleditem ITEM_TYRANITARITE
	end
	
MegaStone_EventScript_ItemBeedrillite::
	addscaleditem ITEM_BEEDRILLITE
	end
	
MegaStone_EventScript_ItemSteelixite::
	addscaleditem ITEM_STEELIXITE
	end
	
MegaStone_EventScript_ItemSablenite::
	addscaleditem ITEM_SABLENITE
	end
	
MegaStone_EventScript_ItemMawilite::
	addscaleditem ITEM_MAWILITE
	end
	
MegaStone_EventScript_ItemSharpedoite::
	addscaleditem ITEM_SHARPEDONITE
	end
	
MegaStone_EventScript_ItemCameruptite::
	addscaleditem ITEM_CAMERUPTITE
	end
	
MegaStone_EventScript_ItemAltarianite::
	addscaleditem ITEM_ALTARIANITE
	end
	
MegaStone_EventScript_ItemGlailite::
	addscaleditem ITEM_GLALITITE
	end
	
MegaStone_EventScript_ItemSalamancite::
	addscaleditem ITEM_SALAMENCITE
	end
	
MegaStone_EventScript_ItemMetagrossite::
	addscaleditem ITEM_METAGROSSITE
	end
	
MegaStone_EventScript_ItemLopunnite::
	addscaleditem ITEM_LOPUNNITE
	end
	
MegaStone_EventScript_ItemGalladite::
	addscaleditem ITEM_GALLADITE
	end
	
MegaStone_EventScript_ItemAudinite::
	addscaleditem ITEM_AUDINITE
	end
	
MegaStone_EventScript_ItemGardevoirite::
	addscaleditem ITEM_GARDEVOIRITE
	end
	
MegaStone_EventScript_ItemCharizardite_X::
	addscaleditem ITEM_CHARIZARDITE_X
	end
	
MegaStone_EventScript_ItemGengarite::
	addscaleditem ITEM_GENGARITE
	end
	
MegaStone_EventScript_ItemGyaradosite::
	addscaleditem ITEM_GYARADOSITE
	end
	
MegaStone_EventScript_ItemManectricite::
	addscaleditem ITEM_MANECTITE
	end
	
MegaStone_EventScript_ItemBanetite::
	addscaleditem ITEM_BANETTITE
	end
	
MegaStone_EventScript_Ampharosite::
	addscaleditem ITEM_AMPHAROSITE
	end
	
MegaStone_EventScript_Lucarionite::
	addscaleditem ITEM_LUCARIONITE
	end
	
MegaStone_EventScript_Garchompite::
	addscaleditem ITEM_GARCHOMPITE
	end
	
MegaStone_EventScript_Medichamite::
	addscaleditem ITEM_MEDICHAMITE
	end	
	
MegaStone_EventScript_Absolite::
	addscaleditem ITEM_ABSOLITE
	end	

MegaStone_EventScript_Pinsirite::
	addscaleditem ITEM_PINSIRITE
	end	
	
MegaStone_EventScript_Scizorite::
	addscaleditem ITEM_SCIZORITE
	end	
	
MegaStone_EventScript_Abomasite::
	addscaleditem ITEM_ABOMASITE
	end	
	
MegaStone_EventScript_Alakazite::
	addscaleditem ITEM_ALAKAZITE
	end
	
MegaStone_EventScript_Mewtwonite_Y::
	addscaleditem ITEM_MEWTWONITE_Y
	end	
	
PrimevalForest_EventScript_ItemGrassKnot::
	addscaleditem ITEM_TM86
	end	
	
PrimevalForest_EventScript_ItemShinyStone::
	addscaleditem ITEM_SHINY_STONE
	end
	
MagmaHideout_3F_3R_EventScript_ItemRedOrb::
	addscaleditem ITEM_RED_ORB
	end
	
RelicCave_EventScript_ItemFossil::
	addscaleditem ITEM_HELIX_FOSSIL
	end
	
Oldale_Ruins_EventScript_ItemTM80::
	addscaleditem ITEM_TM80
	end
	
Route106_EventScript_ItemTM99::
	addscaleditem ITEM_TM99
	end
