	.align 2
gTilesetPalOverrides_General::
	.byte 5
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_General05

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2

	.align 2
gTilesetPalOverrides_Petalburg::
	.byte 8
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_Petalburg08

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2
	
	.align 2
gTilesetPalOverrides_GeneralFRLG_Autumn::
	.byte 0
	.byte TIME_NIGHT
	.2byte 0 @ padding
	.4byte gTilesetPalOverride_GeneralFRLG_Autumn

	.byte 0xFF
	.byte 0
	.byte 0
	.byte 0 @ padding
	.4byte NULL
	.align 2
